apiVersion: v1
kind: Service
metadata:
  name: service-sts-example
spec:
  selector:
    app: stateful
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 8085
    targetPort: 80   
